version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=menegmentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1234
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=menegmentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1234
    ports:
      - "6432:5432"

volumes:
  postgres_data: