# Generated by Django 5.0.4 on 2024-04-16 04:33

import apps.core.choicearreyfield
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scienc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('staff', models.ManyToManyField(to='account.staffprofile')),
                ('student', models.ManyToManyField(to='account.studentprofile')),
                ('scienc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.scienc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonsChedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('deys', apps.core.choicearreyfield.ChoiceArrayField(base_field=models.CharField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')], max_length=32), null=True, size=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.room')),
            ],
        ),
    ]
